mode: auto
silent: false
branchName: full
defaultBranch: 'main'

branches:
  - label: bug
    name: release/1.3.x
    prefix: bugs/
  - label: enhancement
    prefix: features/
  - label: documentation
    prefix: docs/
