categories:
  - title: '🔥 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧹 Maintenance'
    label: 'chore'
  - title: '📜 Documentation'
    label: 'documentation'
  - title: 'CI/CD'
    label: 'ci/cd'
change-template: '- #$NUMBER $TITLE (by @$AUTHOR)'
template: |
  ## Changes

  $CHANGES
