categories:
  - title: '🔥 Features'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug :bug:'
  - title: 'Google Summer of Code 2022'
    label: 'GSoC22'
  - title: '💯 Benchmarking'
    label: 'benchmarking'
  - title: '📜 Documentation'
    label: 'documentation :book:'
  - title: '🧹 Maintenance'
    label: 'chore'
  - title: '🧪 Testing'
    label: 'testing'
  - title: 'Arithmetic'
    label: 'arithmetic'
  - title: 'Array API'
    label: 'array API'
  - title: 'Classification'
    label: 'classification'
  - title: 'Cluster'
    label: 'cluster'
  - title: 'Communication'
    labels:
      - 'io'
      - 'I/O'
      - 'communication'
  - title: 'Complex Math'
    label: 'complex math'
  - title: 'Constants'
    label: 'constants'
  - title: 'Datasets'
    label: 'datasets'
  - title: 'Devices'
    label: 'devices'
  - title: 'DNDarray'
    label: 'dndarray'
  - title: 'Exponential'
    label: 'exponential'
  - title: 'Factories'
    label: 'factories'
  - title: 'Graph'
    label: 'graph'
  - title: 'Indexing'
    label: 'indexing'
  - title: 'Interoperability'
    label: 'interoperability'
  - title: 'Linear Algebra'
    label: 'linalg'
  - title: 'Logical'
    label: 'logical'
  - title: 'Manipulations'
    label: 'manipulation'
  - title: 'Memory'
    label: 'memory'
  - title: 'Naive Bayes'
    label: 'naive Bayes'
  - title: 'Neural Networks'
    labels:
      - 'nn'
      - 'neural net'
  - title: 'Optimization'
    label: 'optim'
  - title: 'Printing'
    label: 'printing'
  - title: 'Random'
    label: 'random'
  - title: 'Regression'
    label: 'regression'
  - title: 'Relational'
    label: 'relational'
  - title: 'Rounding'
    label: 'rounding'
  - title: 'Sanitation'
    label: 'sanitation'
  - title: 'Signal'
    label: 'signal'
  - title: 'Sparse'
    label: 'sparse'
  - title: 'Spatial'
    label: 'spatial'
  - title: 'Statistics'
    label: 'statistics'
  - title: 'Stride Tricks'
    label: 'stride tricks'
  - title: 'Tiling'
    label: 'tiling'
  - title: 'Trigonometrics'
    label: 'trigonometrics'
  - title: 'Types'
    label: 'types'

change-template: '- #$NUMBER $TITLE (by @$AUTHOR)'
category-template: '### $TITLE'
exclude-labels:
- 'workflow'
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
