categories:
  - title: '🔥 Features'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug :bug:'
  - title: '🧹 Maintenance'
    label: 'chore'
  - title: '📜 Documentation'
    label: 'documentation :book:'
  - title: '🧪 Testing'
    label: 'testing'
  - title: '💯 Benchmarking'
    label: 'benchmarking'
change-template: '- #$NUMBER $TITLE (by @$AUTHOR)'
categorie-template: '### $TITLE'
exclude-labels:
- 'workflow'
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
