test:
  image: ubuntu:20.04
  tags:
  - heat
  script:
  - apt update
  - apt -y install build-essential python3-pip
  - DEBIAN_FRONTEND=noninteractive apt -y install libopenmpi-dev openmpi-bin openmpi-doc
  - pip install pytest
  - pip install .
  - mpirun --allow-run-as-root -n 1 python3 -m pytest heat/
  - mpirun --allow-run-as-root -n 2 python3 -m pytest heat/
  - mpirun --allow-run-as-root -n 3 python3 -m pytest heat/
  - mpirun --allow-run-as-root -n 4 python3 -m pytest heat/
  - mpirun --allow-run-as-root -n 5 python3 -m pytest heat/
  - mpirun --allow-run-as-root -n 6 python3 -m pytest heat/
  - mpirun --allow-run-as-root -n 7 python3 -m pytest heat/
  - mpirun --allow-run-as-root -n 8 python3 -m pytest heat/
