test:
  image: nvidia/cuda:11.7.1-runtime-ubuntu22.04
  tags:
    - cuda
    - x86_64
  script:
    - apt update
    - apt -y install build-essential python3-pip curl git
    - curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/helmholtz-analytics/heat/statuses/$CI_COMMIT_SHA
  artifacts:
    when: always
    paths:
      - report/test/report*.xml
    reports:
      junit: report/test/report*.xml
