test:
  image: ubuntu:20.04
  tags:
  - heat
  script:
  - apt update
  - apt -y install build-essential python3-pip
  - DEBIAN_FRONTEND=noninteractive apt -y install libopenmpi-dev openmpi-bin openmpi-doc
  - pip install pytest
  - pip install .
  - mpirun -n 1 python3 -m pytest heat/
  - mpirun -n 2 python3 -m pytest heat/
  - mpirun -n 3 python3 -m pytest heat/
  - mpirun -n 4 python3 -m pytest heat/
