version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - pandoc
    - libopenmpi-dev
  
  jobs:
    pre_build:
      - |
        # Only perform this check for Pull Requests (external builds)
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ]; then
          # Check for changes in:
          # 1. doc/ 
          # 2. heat/ 
          # 3. examples/ or tutorials/ 
          # 4. Config files 
          git diff --name-only $READTHEDOCS_GIT_COMMIT_HASH_BASE $READTHEDOCS_GIT_COMMIT_HASH | grep -E '^(doc/|heat/|examples/|tutorials/|pyproject\.toml|.readthedocs\.yaml)' || exit 18
        fi

sphinx:
  configuration: doc/source/conf.py

python:
  install:
  - method: pip
    path: .
    extra_requirements:
    - docs
