# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - pandoc
    - libopenmpi-dev
  jobs:
    pre_build:
      # Skip builds for PRs labeled with 'automation' or 'chore'
      - |
        if [ -n "$READTHEDOCS_VERSION_TYPE" ] && [ "$READTHEDOCS_VERSION_TYPE" = "external" ]; then
          # This is a PR build, check for labels
          PR_NUMBER=$(echo $READTHEDOCS_VERSION | sed 's/^pr-//')
          if command -v curl > /dev/null 2>&1 && [ -n "$PR_NUMBER" ]; then
            LABELS=$(curl -s "https://api.github.com/repos/helmholtz-analytics/heat/pulls/$PR_NUMBER" | grep -o '"name":"[^"]*"' | grep -E '"name":"(automation|chore)"' || true)
            if [ -n "$LABELS" ]; then
              echo "Skipping build for PR #$PR_NUMBER with automation/chore label"
              exit 183
            fi
          fi
        fi

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/source/conf.py

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
  - method: pip
    path: .
    extra_requirements:
    - docs
