# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - pandoc
    - libopenmpi-dev

  jobs:
    pre_build:
      - |
        # Only perform this check for Pull Requests (external builds)
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ]; then
          # Check for changes in:
          # 1. doc/
          # 2. heat/
          # 3. examples/ or tutorials/
          # 4. Config files
          git diff --name-only $READTHEDOCS_GIT_COMMIT_HASH_BASE $READTHEDOCS_GIT_COMMIT_HASH | grep -q \
            -e '^doc/' \
            -e '^heat/' \
            -e '^examples/' \
            -e '^tutorials/' \
            -e '^pyproject\.toml' \
            -e '^\.readthedocs\.yaml' || exit 18
        fi

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/source/conf.py

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
  - method: pip
    path: .
    extra_requirements:
    - docs
