ignore:
  - "heat/core/regression/lasso/demo.py"
  - "heat/core/regression/lasso/plotfkt.py"
  - "heat/examples/*"
  - "heat/utils/data/mnist.py"
  - "heat/utils/data/_utils.py"
  - "heat/**/test_*.py"

coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 3%
        flags:
          - unit

    patch:
      default:
        # basic
        target: auto
        threshold: 3%
        flags:
          - "unit"

flags:
  unit:
    carryforward: true
    paths:
      - "heat"
