version = 1

# All files
[[annotations]]
path = "**"
SPDX-FileCopyrightText = "Copyright (c) 2019-2026 Forschungszentrum Jülich GmbH, Karlsruher Institut für Technologie KdöR (KIT); Copyright (c) 2019-2025 Deutsches Zentrum für Luft- und Raumfahrt e.V. (DLR)"
SPDX-License-Identifier = "MIT"

# iris dataset
[[annotations]]
path = "heat/datasets/iris*"
SPDX-FileCopyrightText = "R. A. Fisher"
SPDX-License-Identifier = "CC0-1.0"
precedence = "override"

# diabetes dataset
[[annotations]]
path = "heat/datasets/diabetes.h5"
SPDX-FileCopyrightText = "National Institute of Diabetes and Digestive and Kidney Diseases"
SPDX-License-Identifier = "CC0-1.0"
precedence = "override"

# other's logos
[[annotations]]
path = [
    "doc/source/_static/images/dlr_logo.svg",
    "doc/source/_static/images/fzj_logo.svg",
    "doc/source/_static/images/jsc_logo.png",
    "doc/source/_static/images/jupyter.png",
    "doc/source/_static/images/kit_logo.svg",
    "doc/source/_static/images/perun_logo.svg",
]
SPDX-FileCopyrightText = "Copyright lies with the respective trademark owners"
SPDX-License-Identifier = "LicenseRef-Company-Logos"
