name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: ""
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Code snippet triggering the error
      description: Please copy and paste your lines of code.
      render: shell
  - type: textarea
    id: logs
    attributes:
      label: Relevant error message
      description: Please copy and paste your error message.
      render: shell
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of Heat are you running?
      options:
        - 1.2.x
        - 1.1.x
        - main (development branch)
    validations:
      required: true
  - type: dropdown
    id: python-version
    attributes:
      label: Python version
      description: What Python version?
      options:
        - 3.8
        - 3.9
        - 3.10
        - 3.7
  - type: dropdown
    id: pytorch-version
    attributes:
      label: PyTorch version
      description: What PyTorch version?
      options:
        - 1.11
        - 1.10
        - 1.9
        - 1.8
        - 1.7
