name: "\U0001F41E Bug report"
description: File a bug report to help us improve.
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Code snippet triggering the error
      description: Please copy and paste your lines of code.
      render: shell
  - type: textarea
    id: logs
    attributes:
      label: Error message or erroneous outcome
      description: Please copy and paste your error.
      render: shell
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of Heat are you running?
      options:
        - main (development branch)
        - 1.7.x
        - other
    validations:
      required: true
  - type: dropdown
    id: python-version
    attributes:
      label: Python version
      description: What Python version?
      options:
        - 3.14
        - 3.13
        - 3.12
        - 3.11
        - '3.10'
  - type: dropdown
    id: pytorch-version
    attributes:
      label: PyTorch version
      description: What PyTorch version?
      options:
        - 2.9
        - 2.8
        - 2.7
        - 2.6
        - 2.5
        - 2.4
        - 2.3
        - 2.2
        - other
  - type: textarea
    id: mpi-version
    attributes:
      label: MPI version
      description: OpenMPI, ParaStation, IntelMPI version?
      render: shell
