name: "📋 NEP 29 Compliance Check"
description: Check and update NEP 29 compliance for upcoming release
title: "[Release Prep]: NEP 29 Compliance Check for v{version}"
labels: ["release-prep", "compliance", "NEP29"]

body:
  - type: markdown
    attributes:
      value: |
        This issue tracks NEP 29 compliance verification for the upcoming Heat release.
        NEP 29 defines minimum supported versions for the scientific Python ecosystem.

  - type: checkboxes
    id: nep29-tasks
    attributes:
      label: NEP 29 Compliance Tasks
      description: Complete these tasks to ensure NEP 29 compliance
      options:
        - label: Review current NEP 29 minimum supported versions
          required: false
        - label: Check Python version support in pyproject.toml
          required: false
        - label: Check NumPy version support in requirements
          required: false
        - label: Check PyTorch version support in requirements
          required: false
        - label: Update bug report template with current supported versions
          required: false
        - label: Update CI matrix to test minimum supported versions
          required: false
        - label: Update documentation with supported versions
          required: false
        - label: Verify all dependencies meet NEP 29 requirements
          required: false

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any additional notes or findings regarding NEP 29 compliance
      placeholder: Add any version compatibility issues or notes here...

  - type: textarea
    id: version-updates
    attributes:
      label: Version Updates Required
      description: List any version updates needed for compliance
      placeholder: |
        Example:
        - Python: Update minimum from 3.8 to 3.9
        - NumPy: Update minimum from 1.20 to 1.21
        - PyTorch: Update minimum from 1.10 to 1.11
