name: "✨ Release Highlights Selection"
description: Select highlights for the upcoming release
title: "[Release Prep]: Select Highlights for v{version}"
labels: ["release-prep", "highlights", "release-notes"]

body:
  - type: markdown
    attributes:
      value: |
        This issue tracks the selection of highlights for the upcoming Heat release.
        Review merged PRs and features to identify key highlights for the release notes.
        
  - type: textarea
    id: major-features
    attributes:
      label: Major New Features
      description: List major new features added in this release
      placeholder: |
        Example:
        - New distributed FFT implementation
        - Support for sparse tensor operations
        - Enhanced GPU memory management
        
  - type: textarea
    id: performance-improvements
    attributes:
      label: Performance Improvements
      description: List significant performance improvements
      placeholder: |
        Example:
        - 2x speedup in matrix multiplication for large matrices
        - Reduced memory usage in distributed operations
        - Optimized communication patterns
        
  - type: textarea
    id: api-changes
    attributes:
      label: API Changes & Deprecations
      description: List important API changes, deprecations, or breaking changes
      placeholder: |
        Example:
        - Deprecated old_function() in favor of new_function()
        - Changed default behavior of operation X
        - Removed previously deprecated feature Y
        
  - type: textarea
    id: bug-fixes
    attributes:
      label: Notable Bug Fixes
      description: List important bug fixes that users should know about
      placeholder: |
        Example:
        - Fixed memory leak in distributed operations
        - Resolved incorrect results in edge case X
        - Fixed compatibility issue with PyTorch 2.x
        
  - type: textarea
    id: documentation
    attributes:
      label: Documentation & Examples
      description: List significant documentation or example improvements
      placeholder: |
        Example:
        - New tutorial on distributed computing
        - Updated getting started guide
        - Added performance benchmarking examples
        
  - type: checkboxes
    id: highlight-tasks
    attributes:
      label: Highlight Selection Tasks
      description: Complete these tasks for highlight selection
      options:
        - label: Review all merged PRs since last release
          required: false
        - label: Identify major features from PR labels and descriptions
          required: false
        - label: Contact contributors for feature descriptions
          required: false
        - label: Write draft highlight descriptions
          required: false
        - label: Get team approval for selected highlights
          required: false
        - label: Update CITATION.cff with new contributors
          required: false