name: "\U0001F6A8 Vulnerability Report"
description: Report a security vulnerability in our project.
title: "[VULNERABILITY]:  "
labels: ["security, High Priority"]
assignees: ["mtar, bhagemeier, ClaudiaComito"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a security vulnerability! Your assistance helps us keep our library secure.
  - type: textarea
    id: affected-versions
    attributes:
      label: Affected Version(s)
      description: List the affected versions of the library.
    validations:
      required: true
  - type: textarea
    id: severity
    attributes:
      label: Severity
      description: Specify the severity of the vulnerability (e.g., Low/Medium/High/Critical).
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the security vulnerability.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Outline the steps to reproduce the vulnerability, including any relevant code snippets or configuration settings.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Explain what you expected to happen when following the steps above.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Describe what actually happened when you followed the steps above, highlighting the security issue.
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Discuss the potential impact of this vulnerability, including any possible consequences or risks associated with its exploitation.
    validations:
      required: true
  - type: textarea
    id: proof-of-concept
    attributes:
      label: Proof of Concept (Optional)
      description: If applicable, provide a proof of concept (POC) or exploit code to demonstrate the vulnerability. Do not disclose sensitive information.
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Include any additional information or context that you believe is relevant to this vulnerability report.
  - type: textarea
    id: proposed-fix
    attributes:
      label: Proposed Fix (Optional)
      description: If you have a suggested fix or mitigation for this vulnerability, please provide details here. Your input is valuable.
  - type: textarea
    id: attachments
    attributes:
      label: Attachments (Optional)
      description: If you have any relevant files or screenshots, please attach them here.
  - type: textarea
    id: disclosure-timeline
    attributes:
      label: Disclosure Timeline (Optional)
      description: If you have a preferred timeline for the disclosure of this vulnerability, please specify it here. We typically follow responsible disclosure practices and will coordinate with you on the disclosure process.
  - type: textarea
    id: additional-contact-info
    attributes:
      label: Additional Contact Information (Optional)
      description: If you prefer to be contacted through an alternate method or have other contact preferences, please specify them here.
  - type: markdown
    attributes:
      value: |
        ---

        **Note**: By submitting this report, you agree to follow responsible disclosure practices and to work with the maintainers to coordinate the resolution and disclosure of this vulnerability.

        Thank you for helping us improve the security of our library!
