#!/bin/bash

export HEAT_BENCHMARK_DEVICE=cpu
export HEAT_BENCHMARK_NUM_SAMPLES=5

export HEAT_BENCHMARK_NUM_THREADS_PER_MPI_PROC=6
export HEAT_BENCHMARK_NUM_CPUS_PER_NODE=24
export HEAT_BENCHMARK_MAX_NUM_MPI_PROCS=16
export HEAT_BENCHMARK_TIME_PER_RUN=00:01:00

for j in 1 2 3 4
do
    export HEAT_BENCHMARK_NUM_MPI_PROCS=$j
    export HEAT_BENCHMARK_NUM_USED_CPUS=$(($HEAT_BENCHMARK_NUM_MPI_PROCS*$HEAT_BENCHMARK_NUM_THREADS_PER_MPI_PROC))
    if (($HEAT_BENCHMARK_NUM_USED_CPUS % $HEAT_BENCHMARK_NUM_CPUS_PER_NODE == 0))
    then
        export HEAT_BENCHMARK_NUM_NODES=$(($HEAT_BENCHMARK_NUM_MPI_PROCS*$HEAT_BENCHMARK_NUM_THREADS_PER_MPI_PROC/$HEAT_BENCHMARK_NUM_CPUS_PER_NODE))
    else
        export HEAT_BENCHMARK_NUM_NODES=$(($HEAT_BENCHMARK_NUM_MPI_PROCS*$HEAT_BENCHMARK_NUM_THREADS_PER_MPI_PROC/$HEAT_BENCHMARK_NUM_CPUS_PER_NODE + 1))
    fi
    export OMP_NUM_THREADS=$HEAT_BENCHMARK_NUM_THREADS_PER_MPI_PROC
    export MKL_NUM_THREADS=$HEAT_BENCHMARK_NUM_THREADS_PER_MPI_PROC
    sbatch --nodes $HEAT_BENCHMARK_NUM_NODES --ntasks $HEAT_BENCHMARK_NUM_MPI_PROCS --cpus-per-task $HEAT_BENCHMARK_NUM_THREADS_PER_MPI_PROC --time $HEAT_BENCHMARK_TIME_PER_RUN --gres gpu:0 run_my_script_cpu.sh
done
