#!/bin/bash

export HEAT_BENCHMARK_DEVICE=cpu
export HEAT_BENCHMARK_NUM_SAMPLES=5

export HEAT_BENCHMARK_NUM_THREADS_PER_MPI_PROC=2
export HEAT_BENCHMARK_NUM_MPI_PROCS_PER_NODE=6
export HEAT_BENCHMARK_MAX_NUM_NODES=2
export HEAT_BENCHMARK_TIME_PER_RUN=00:01:00

for ((j=0;2**j<=$HEAT_BENCHMARK_MAX_NUM_NODES;j++))
do
    export HEAT_BENCHMARK_NUM_NODES=$((2**$j))
    export HEAT_BENCHMARK_NUM_MPI_PROCS=$(($HEAT_BENCHMARK_NUM_NODES*$HEAT_BENCHMARK_NUM_MPI_PROCS_PER_NODE))
    export OMP_NUM_THREADS=$HEAT_BENCHMARK_NUM_THREADS_PER_MPI_PROC
    export MKL_NUM_THREADS=$HEAT_BENCHMARK_NUM_THREADS_PER_MPI_PROC
    sbatch --nodes $HEAT_BENCHMARK_NUM_NODES --ntasks $HEAT_BENCHMARK_NUM_MPI_PROCS --cpus-per-task $HEAT_BENCHMARK_NUM_THREADS_PER_MPI_PROC --time $HEAT_BENCHMARK_TIME_PER_RUN --gres gpu:0 run_my_script_cpu.sh
done
