#!/bin/bash

export HEAT_BENCHMARK_DEVICE=cpu
export HEAT_BENCHMARK_NUM_SAMPLES=5

export HEAT_BENCHMARK_NUM_NODES=1
export HEAT_BENCHMARK_TIME_PER_RUN=00:01:00

for j in 2 3 4 6 12 24
do
	export HEAT_BENCHMARK_NUM_THREADS_PER_MPI_PROC=$j
	export HEAT_BENCHMARK_NUM_MPI_PROCS=$HEAT_BENCHMARK_NUM_NODES   # only one MPI-process per node
	export OMP_NUM_THREADS=$HEAT_BENCHMARK_NUM_THREADS_PER_MPI_PROC
	export MKL_NUM_THREADS=$HEAT_BENCHMARK_NUM_THREADS_PER_MPI_PROC
	sbatch --nodes $HEAT_BENCHMARK_NUM_NODES --ntasks $HEAT_BENCHMARK_NUM_MPI_PROCS --cpus-per-task $HEAT_BENCHMARK_NUM_THREADS_PER_MPI_PROC --time $HEAT_BENCHMARK_TIME_PER_RUN --gres gpu:0 run_my_script_cpu.sh
done
