name: Trigger Codebase Tests
description: "Trigger tests on Codebase for performance testing and analysis."
inputs:
  branch:
    description: "The branch to trigger tests on. Defaults to 'main'."
    required: false
    default: "main"
  sha:
    description: "The commit SHA to trigger tests on. Defaults to the current commit."
    required: false
    default: "${{ github.sha }}"
  pr_number:
    description: "The pull request number to trigger tests on. Defaults to the current PR number."
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
      with:
        egress-policy: audit
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Trigger tests for PR
      if : ${{ inputs.pr_number == '' }}
      env:
        PIPE_TRIGGER_TOKEN: ${{ secrets.CB_PIPELINE }}
        BRANCH: ${{ inputs.branch }}
        PR_NUMBER: ${{ inputs.pr_number }}
      run: |
        curl -s -X POST \
          --fail-with-body \
          -F "token=$PIPE_TRIGGER_TOKEN" \
          -F "ref=main" \
          -F "variables[GHBRANCH]=$BRANCH" \
          https://codebase.helmholtz.cloud/api/v4/projects/7930/trigger/pipeline
