import numpy as np
import numpy.linalg
import numpy.fft
import numpy.ma
import numpy.random
import scipy.signal
import scipy.ndimage
import scipy.sparse
import heat

# 1. Define the architecture tracking metadata dynamically
# Format: (Table Title, Source Reference Module, Target Heat Module, Display Prefix)
categories = [
    ("NumPy Core Operations", np, heat, ""),
    ("NumPy LinAlg Operations", np.linalg, getattr(heat, "linalg", None), "linalg."),
    ("NumPy FFT Operations", np.fft, getattr(heat, "fft", None), "fft."),
    ("NumPy Masked Array Operations", np.ma, getattr(heat, "ma", None), "ma."),
    ("NumPy Random Operations", np.random, getattr(heat, "random", None), "random."),
    ("SciPy Signal Operations", scipy.signal, getattr(heat, "signal", None), "signal."),
    ("SciPy NDImage Operations", scipy.ndimage, getattr(heat, "ndimage", None), "ndimage."),
    ("SciPy Sparse Operations", scipy.sparse, getattr(heat, "sparse", None), "sparse."),
]

# 2. Initialize the markdown file and write SEO optimized headers
f = open("coverage_tables.md", "w")

# MyST-compatible SEO block configuration
f.write(
    "```{meta}\n"
    ":description: Check the API compatibility matrix for Heat, featuring memory-distributed "
    "and multi-GPU accelerated alternatives to standard NumPy and SciPy functions.\n"
    "```\n\n"
)

f.write("# NumPy & SciPy API Compatibility Matrices\n\n")

f.write(
    "This API coverage matrix tracks Heat's compatibility with standard NumPy and SciPy libraries. "
    "It maps standard functions to their respective Heat implementations, highlighting "
    "operations engineered with native support for multi-GPU hardware acceleration and "
    "memory-distributed computing across cluster environments.\n\n"
)
f.write("This file is automatically generated by `./scripts/numpy_coverage_tables.py`.\n\n")
f.write(
    "Please do not edit this file directly, but instead edit `./scripts/numpy_coverage_tables.py` "
    "and run it to regenerate these tables.\n\n"
)

# 3. Dynamic Table of Contents Generation
f.write("## Table of Contents\n")
for i, (title, _, _, _) in enumerate(categories):
    anchor_link = title.lower().replace(" ", "-")
    f.write(f"{i + 1}. [{title}](#{anchor_link})\n")
f.write("\n")

# 4. Process Modules Dynamically and Generate Matrix Tables
for title, source_mod, heat_mod, prefix in categories:
    f.write(f"## {title}\n")
    f.write("[Back to Table of Contents](#table-of-contents)\n\n")

    # Extract all public callables (functions/classes) from the source module reference
    public_functions = [
        func_name for func_name in dir(source_mod)
        if not func_name.startswith('_') and callable(getattr(source_mod, func_name))
    ]

    table_rows = []

    for func_name in public_functions:
        # Evaluate if the underlying Heat sub-module explicitly provides this attribute
        if heat_mod and hasattr(heat_mod, func_name):
            support_status = "✅"  # Green checkmark for supported functions
        else:
            support_status = "❌"  # Red cross for unsupported functions

        display_name = f"{prefix}{func_name}"

        # Create the dynamic issue tracker URL matching the function signature
        issue_url = f"https://github.com/helmholtz-analytics/heat/issues?q=is%3Aissue+is%3Aopen+{display_name}"
        table_row = f"| {display_name} | {support_status} | [Search]({issue_url}) |"
        table_rows.append(table_row)

    # Construct the Markdown Table layout
    table_header = f"| {title} | Heat Support Status | Issues |\n|---|---|---|\n"
    markdown_table = table_header + "\n".join(table_rows)

    f.write(markdown_table)
    f.write("\n\n")

f.close()
print("Successfully generated coverage_tables.md dynamically!")
