name: CI run

on:
  push:
    branches:
      - 'main'
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://codebase.helmholtz.cloud/haf/heat"
      env:
        FORCE_PUSH: "true"
        GITLAB_HOSTNAME: "codebase.helmholtz.cloud"
        GITLAB_USERNAME: ""
        GITLAB_PASSWORD: ${{ secrets.GITLAB_TOKEN_1 }}
        GITLAB_PROJECT_ID: "845"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
