name: Mirror and run GitLab CI

on:
  push:
    paths:
      - 'heat/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: autotelic/action-wait-for-status-check@v1
      id: wait-for-status
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        statusName: "pre-commit.ci - pr"

    - name: Mirror + trigger CI
      if: steps.wait-for-status.outputs.state == 'success'
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.hzdr.de/haf/heat"
      env:
        FORCE_PUSH: "true"
        GITLAB_HOSTNAME: "gitlab.hzdr.de"
        GITLAB_USERNAME: ""
        GITLAB_PASSWORD: ${{ secrets.GITLAB_TOKEN_1 }}
        GITLAB_PROJECT_ID: "845"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
