name: CI Status

on:
  status:
    branches:
      - main
  
jobs:
  if_error_or_failure:
    runs-on: ubuntu-latest
    if: >-
      github.event.context == 'continuous-integration/codebase' &&
      (github.event.state == 'error' ||
      github.event.state == 'failure')
    steps:
      - run: |
          exit 1
  if_success:
    runs-on: ubuntu-latest
    if: >-
      github.event.context == 'continuous-integration/codebase' &&
      github.event.state == 'success'
    steps:
      - run: |
          exit 0