name: GPU Test Submission

on: push

jobs:
  submit-gpu-tests:
    name: Submit GPU test batch job
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HDFML_HOST }}
          username: ${{ secrets.HDFML_NAME }}
          key: ${{ secrets.HDFML_KEY }}
          passphrase: ${{ secrets.HDFML_PASSPHRASE }}
          envs: GITHUB_SHA,GITHUB_REPOSITORY
          script: |
            cd ${{ secrets.HDFML_DIR }}
            cd heat
            git fetch
            git checkout -f $GITHUB_SHA
            cd ..
            export SHA=$GITHUB_SHA
            export STATUS_TOKEN=${{ secrets.GITHUB_TOKEN }}
            export REPOSITORY=$GITHUB_REPOSITORY
            sbatch test_batch_script.sh
            curl -H "Content-Type: application/json" -H "Authorization: token $STATUS_TOKEN" -X POST -d "{\"state\": \"pending\", \"description\": \"GPU Test Status $?\", \"context\": \"GPU Testing\"}" https://api.github.com/repos/$REPOSITORY/statuses/$SHA
