on:
    push:
      branches:
        - 'workflows/gh-action-merge-release-changes-into-main'
env:
    base_branch: ${{ github.ref }}
    working_branch: workflows/merge-release-changes-to-main
permissions:
    contents: write
    issues: write
    pull-requests: write

jobs:
    check_out:
        runs-on: ubuntu-latest
        if: ${{ github.repository }} == 'hemlholtz-analytics/heat'
        steps:
            - uses: actions/checkout@v3
              with:
                token: ${{ secrets.GHACTIONS }}
                ref: '${{ env.base_branch }}'
            - name: Delete working branch if it already exists
              run: git push --delete origin ${{ env.working_branch }} || true
            - name: Create working branch
              run: |
                git checkout -b ${{ env.working_branch }}
                git config --global user.name 'ClaudiaComito'
                git config --global user.email 'c.comito@fz-juelich.de@users.noreply.github.com'
                git commit -am "Push new branch"
                git push --set-upstream origin ${{ env.working_branch }}
    pull_request:
        needs: check_out
        runs-on: ubuntu-latest
        steps:
        - name: Create a pull request
          uses: peter-evans/create-pull-request@v3
          with:
            token: ${{ secrets.GHACTIONS }}
            commit-message: 'Merge release changes to main'
            title: 'Merge release changes to main'
            body: 'This PR merges changes from release branch to main branch'
            branch: '${{ env.working_branch }}'
            base: main
