name: On Push Main
on:
  push:
    branches:
      - main
jobs:
  test-and-bench-main:
    name: Testing and
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.sha }}
      - uses: ./.github/actions/trigger_codebase_tests
        with:
          branch: "main"
          sha: ${{ github.sha}}
          trigger_token: ${{ secrets.CX_TRIGGER_TOKEN }}
      - uses: ./.github/actions/trigger_codebase_benchmarks
        with:
          branch: "main"
          sha: ${{ github.sha}}
          author: ${{ 'heat_team' }}
          trigger_token: ${{ secrets.CX_TRIGGER_TOKEN }}
