name: On Push Main
on:
  push:
    branches:
      - main
      - stable
    paths:
      - 'heat/**'
      - 'tests/**'
      - 'pyproject.toml'
jobs:
  codebase-test-and-bench-main:
    name: Codebase Tests and Benchmarks
    if: ${{ !github.event.repository.fork }}
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.sha }}
      - uses: ./.github/actions/trigger_codebase_tests
        with:
          branch: "main"
          sha: ${{ github.sha}}
          trigger_token: ${{ secrets.CX_TRIGGER_TOKEN }}
      - uses: ./.github/actions/trigger_codebase_benchmarks
        with:
          branch: "main"
          sha: ${{ github.sha}}
          author: 'heat_team'
          trigger_token: ${{ secrets.CX_TRIGGER_TOKEN }}
  gh-matrix-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        py-version:
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
        mpi: [ 'mpich' ]
        pytorch-version:
          - 'torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1'
          - 'torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1'
          - 'torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1'
          - 'torch==2.6.0 torchvision==0.21.0 torchaudio==2.6.0'
          - 'torch==2.7.1 torchvision==0.22.1 torchaudio==2.7.1'
          - 'torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0'
          - 'torch==2.9.1 torchvision==0.24.1 torchaudio==2.9.1'
          - 'torch==2.10.0 torchvision==0.25.0 torchaudio==2.10.0'
          - 'torch==2.11.0 torchvision==0.26.0 torchaudio==2.11.0'
        exclude:
          - py-version: '3.14'
            pytorch-version: 'torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1'
          - py-version: '3.14'
            pytorch-version: 'torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1'
          - py-version: '3.14'
            pytorch-version: 'torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1'
          - py-version: '3.14'
            pytorch-version: 'torch==2.6.0 torchvision==0.21.0 torchaudio==2.6.0'
          - py-version: '3.14'
            pytorch-version: 'torch==2.7.1 torchvision==0.22.1 torchaudio==2.7.1'
          - py-version: '3.14'
            pytorch-version: 'torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0'
          - py-version: '3.13'
            pytorch-version: 'torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1'
          - py-version: '3.13'
            pytorch-version: 'torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1'
          - py-version: '3.13'
            pytorch-version: 'torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1'

    name: Python ${{ matrix.py-version }} with ${{ matrix.pytorch-version }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.sha }}
      - uses: ./.github/actions/gh_tests
        with:
          mode: "full"
          py-version: ${{ matrix.py-version }}
          mpi: ${{ matrix.mpi }}
          pytorch-version: ${{ matrix.pytorch-version }}
  check_reuse_compliance:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    name: Check REUSE compliance
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.14'
          architecture: x64

      - name: Install REUSE
        run: |
          pip install reuse

      - name: Run linter
        run: |
          reuse lint
