name: On Push Other Branches
on:
  push:
    branches-ignore:
      - main
      - dependabot/**
jobs:
  test-branch:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        py-version:
          - '3.11' # Oldest supported
          - '3.14' # Latest stable
        mpi: [ 'openmpi' ]
        install-options: [ '.', '.[hdf5,netcdf,pandas,zarr]' ]
        pytorch-version:
          - 'torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1'   # Oldest supported
          - 'torch==2.9.1 torchvision==0.24.1 torchaudio==2.9.1'   # JSC Stage 2026
          - 'torch==2.11.0 torchvision==0.26.0 torchaudio==2.11.0' # Latest stable
        exclude:
          - py-version: '3.14'
            pytorch-version: 'torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1'
    name: Python ${{ matrix.py-version }} with ${{ matrix.pytorch-version }}; options ${{ matrix.install-options }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.sha }}
      - uses: ./.github/actions/gh_tests
        with:
          mode: "full"
          py-version: ${{ matrix.py-version }}
          mpi: ${{ matrix.mpi }}
          install-options: ${{ matrix.install-options }}
          pytorch-version: ${{ matrix.pytorch-version }}
