name: On Push Support
on:
  push:
    branches:
      - 'support/**'
jobs:
  codebase-test-support:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.sha }}
      - uses: ./.github/actions/trigger_codebase_tests
        with:
          branch: ${{ github.head_ref}}
          sha: ${{ github.sha}}
          trigger_token: ${{ secrets.CX_TRIGGER_TOKEN }}
