name: On push to main
on:
  push:
    branches:
      - main
jobs:
  trigger-ci:
    name: Trigger CI
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/trigger_codebase_tests
        with:
          branch: "main"
          sha: ${{ github.sha}}
          trigger_token: ${{ secrets.CX_TRIGGER_TOKEN }}
  trigger-benchmarks:
    name: Trigger Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/trigger_codebase_benchmarks
        with:
          branch: "main"
          sha: ${{ github.sha}}
          author: ${{ 'heat_team' }}
          trigger_token: ${{ secrets.CX_TRIGGER_TOKEN }}
