name: Release Drafter

on:
  pull_request:
    types: [opened, reopened]
permissions:
  contents: read

jobs:

  update_release_draft:
    permissions:
      contents: write  # for release-drafter/release-drafter to create a github release
      pull-requests: write  # for release-drafter/release-drafter to add label to PR
    runs-on: ubuntu-latest
    steps:
      - name: Exit if secret is missing
        run: |
          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "Secret GITHUB_TOKEN not set, skipping job."
            exit 0
          fi

      - name: Harden Runner
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit

      - uses: release-drafter/release-drafter@5de93583980a40bd78603b6dfdcda5b4df377b32 # v7.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: 'stable'
          name: ${{ github.ref_name }} - Draft release
          config-name: rd-release-config.yml
